apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: hello-world
  title: Hello World
  description: scaffolder Hello, World template demo
spec:
  owner: guest
  type: api

  parameters:
    - title: Tell us about your project?
      properties:
        repoSelectWorking:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: Which repository to update
            description: Select the repository component to update
            path: catalog/entities/by-query
            params:
              filter: "kind=component,metadata.tags.serverless-typescript,relations.ownedBy=group:{{ identity.userEntityRef }}"
              fields: "kind,metadata.annotations"
              limit: "1000"
            arraySelector: items
            valueSelector: metadata.annotations["github.com/project-slug"]
        repoSelectBroken:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: Which repository to update
            description: Select the repository component to update
            path: catalog/entities/by-query
            params:
              filter: "kind=component,metadata.tags.serverless-typescript,relations.ownedBy=group:{{ identity.ownershipEntityRefs | join(',relations.ownedBy=group:') }}"
              fields: "kind,metadata.annotations"
              limit: "1000"
            arraySelector: items
            valueSelector: metadata.annotations["github.com/project-slug"]

  steps:
    - action: debug:log
      input:
        message: "User entity groups"
        extra: ${{ user.entity.spec.memberOf }}
