site_name: Root docs

nav:
  - Home: index.md
  - Local development: local-development.md
  - Feature Testing: feature-testing.md
  - Big ToC: big-table-of-contents.md
  - TestDoc: test-doc.md
  - Embedded Lucid Chart: testing-lucid.md
  - Subdirectory docs:
    - mycomponent: '!include ./sub-dir-documentation/mkdocs.yml'

docs_dir: docs

plugins:
  - search
  - charts
  - techdocs-core
  - monorepo
extra_javascript:
  - https://cdn.jsdelivr.net/npm/vega@5
  - https://cdn.jsdelivr.net/npm/vega-lite@5
  - https://cdn.jsdelivr.net/npm/vega-embed@6

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: vegalite
          class: vegalite
          format: !!python/name:mkdocs_charts_plugin.fences.fence_vegalite

