# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debugMsg:
        description: 'Debug Message'
        required: false
        default: 'Printing default Debug message, no input provided'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: 'Print debug message'
      shell: bash
      run: |
        echo "${{ inputs.debugMsg }}"

    - uses:  RoadieHQ/backstage-entity-validator@v0.1.0
      with:
        path: 'catalog-info-1.yaml'
